services:
  mongo:
    image: mongo:7
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build:
      context: ./backend
    container_name: backend
    ports:
      - "4000:4000"
    depends_on:
      - mongo
    restart: unless-stopped
    environment:
      - MONGO_URI=mongodb://mongo:27017/your-database

  frontend:
    build:
      context: ./frontend
      args:
      - VITE_API_URL=http://localhost:4000
    container_name: frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  mongo_data:
